name: all_peoples_church_clone
description: APC mobile app (partial) - Supabase content library wiring
version: 0.0.1
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Updated to a modern supabase_flutter version that is published and resolvable.
  supabase_flutter: ^2.10.3
  http: ^0.13.6
  url_launcher: ^6.1.10
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
